# Generated by Django 2.2.4 on 2019-08-27 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourniseur',
            name='date_create',
        ),
        migrations.AddField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 27, 22, 7, 7, 403750), null=True),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='tele',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
