# Generated by Django 2.2.4 on 2019-08-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190827_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourniseur',
            name='created_at',
        ),
    ]
