# Generated by Django 2.2.4 on 2019-08-27 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_fourniseur_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 27, 22, 11, 48, 251529), null=True),
        ),
    ]
