# Generated by Django 2.2.4 on 2019-08-29 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_fourniseur_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 29, 20, 35, 24, 177419), null=True),
        ),
    ]
