# Generated by Django 2.2.4 on 2019-08-29 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190829_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sortie',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 29, 21, 13, 2, 111748), null=True),
        ),
    ]
