# Generated by Django 2.2.4 on 2019-08-31 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20190831_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 19, 11, 53, 957639), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 19, 11, 53, 969608), null=True),
        ),
    ]
