# Generated by Django 2.2.4 on 2019-09-06 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20190906_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 6, 23, 10, 23, 777167), null=True),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 6, 23, 10, 23, 765199), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 6, 23, 10, 23, 776169), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
