# Generated by Django 2.2.4 on 2019-09-07 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20190906_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 7, 17, 24, 28, 714813), null=True),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 7, 17, 24, 28, 706569), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 7, 17, 24, 28, 714813), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 7, 17, 24, 28, 714813), null=True),
        ),
    ]
