# Generated by Django 2.2.4 on 2019-09-10 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20190907_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 0, 35, 13, 212783), null=True),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 0, 35, 13, 212783), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 0, 35, 13, 212783), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 0, 35, 13, 212783), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='entree_avoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Entree'),
        ),
        migrations.CreateModel(
            name='AvoirSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_sortie', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 0, 35, 13, 212783), null=True)),
                ('entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Entree')),
            ],
        ),
        migrations.CreateModel(
            name='AvoirEntree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_entree', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sortie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Sortie')),
            ],
        ),
    ]
