# Generated by Django 2.2.4 on 2019-09-14 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20190911_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoirentree',
            name='qte_entree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avoirsortie',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 14, 22, 59, 50, 752071), null=True),
        ),
        migrations.AlterField(
            model_name='avoirsortie',
            name='qte_sortie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 14, 22, 59, 50, 751043), null=True),
        ),
        migrations.AlterField(
            model_name='entree',
            name='qte_entree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 14, 22, 59, 50, 740105), null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qte_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qte_stock_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 14, 22, 59, 50, 751043), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 14, 22, 59, 50, 750082), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='qte_sortie',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
