# Generated by Django 2.2.4 on 2019-09-15 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20190914_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_achat',
        ),
        migrations.AddField(
            model_name='entree',
            name='prix_achat',
            field=models.FloatField(default=0, verbose_name="Prix D'achat"),
        ),
        migrations.AlterField(
            model_name='avoirsortie',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 47, 17, 122281), null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 47, 17, 121283), null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=20, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 47, 17, 118293), null=True),
        ),
        migrations.AlterField(
            model_name='fourniseur',
            name='prenom',
            field=models.CharField(max_length=20, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 47, 17, 120287), null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='date_sortie',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 47, 17, 120287), null=True),
        ),
    ]
